### PR TITLE
Added 'VERSION' statement to the LEF parser

### PR DESCRIPTION
**Pull request by nicolati**
Hi Jeff,
I'm using a real LEF/DEF, dumped from IC Compiler.
The LEF is empty, unfortunately, so I can test few things...
VERSION statement is something needed, though.

Please review the diff, since I have never used Boost Parser... :)

Fra

### CODE REVIEW

**Comment by nicolati** [comment]
Removed the order of some DEF statements.
Added an initial hint for parsing the DIVIDERCHAR statement.

Fra

**Comment by jefftrull** [comment]
Thanks so much for this PR!  I like the VERSION support.  I might do the DIVIDERCHAR differently though, and the order of items in the DEF needs to be handled in a more general way.  I will make some notes.  Would you be willing to send a PR with just the LEF VERSION change?

**Comment by nicolati** [comment]
Hi Jeff,
I didn't understand everything, because the posts are sort of random! :)
Said that, do the modifications you want, since I'm not really a user of Boost, so I don't know how to use it. Dividechar I think is the only one requires strings, but yes you can do quote-char-quote. It's the same thing is this case and it's more efficient, since it's every time a char! :)

Fra

**Comment by jefftrull** [comment]
Ah the comments look better in the commit itself instead of the PR: https://github.com/nicolati/EDASkel/commit/2eb913a64c179d08bac8c0698de9ffbbdd9fda2b

**Comment by jefftrull** [comment]
Thanks again for your PR.  I am going to fix these things [in my own way](https://github.com/jefftrull/EDASkel/compare/nicolati_bugs?expand=1) :)

Please do keep sending bug reports and PRs!

**Pull request closed without merging**
